---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.359.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.72.0
  - name: jesseduffield/lazygit@v0.49.0
  - name: jesseduffield/lazydocker@v0.24.1
  - name: x-motemen/ghq@v1.8.0
  - name: junegunn/fzf@v0.61.3
  - name: sharkdp/bat@v0.25.0
  - name: sharkdp/fd@v10.2.0
  - name: go-task/task@v3.43.3
  - name: lsd-rs/lsd@v1.1.5
  - name: BurntSushi/ripgrep@14.1.1
  - name: XAMPPRocky/tokei@v12.1.2
  - name: dandavison/delta@0.18.2
  - name: ClementTsang/bottom@0.10.2
  - name: muesli/duf@v0.8.1
  - name: Nukesor/pueue/pueue@v4.0.0
  - name: dalance/procs@v0.14.10
