[tools]
java = "temurin-21.0.7+6.0.LTS"
lua = "5.4.7"
node = "23.11.1"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
pnpm = "10.11.0"
sbt = "1.11.0"
usage = "2.1.1"
yarn = "4.5.3"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
