[tools]
atlas = "latest"
gotestsum = "latest"
lefthook = "latest"
lua = "latest"
node = "latest"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
pnpm = "latest"
usage = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
